### PR TITLE
Fix tapret PSBT commitments. Closes #23

### LINKED ISSUE #23: Tapret commitments bug with PSBT
PSBT receives invalid script pubkey: instead of taproot v1 output it gets the taproot script tree leaf with op_return code.

More details: https://github.com/BP-WG/bp-core/discussions/20

### PR DESCRIPTION
**Pull request by dr-orlovsky**
Alternative to #22

### CODE REVIEW

**Comment by crisdut** [comment]
Hi @dr-orlovsky,

I found two issues in my tests. See below:

1. **`convolve_commit`always returns `PsbtCommitError::TapTreeError`:** This occurs because the method adds a HiddenNode when reconstructing the TapTree. The `Taptree::from_builder` causes a `IncompleteTapTree::HiddenParts` error.

2. **The embed commit does not use the `PSBT_OUT_TAPRET_HOST`:** the method `TaprootScriptTree::embed_commit` define the DfsPath as Last instead of uses the value of the `PSBT_OUT_TAPRET_HOST`.

**Comment by crisdut** [comment]
> 1. **`convolve_commit`always returns `PsbtCommitError::TapTreeError`:** This occurs because the method adds a HiddenNode when reconstructing the TapTree. The `Taptree::from_builder` causes a `IncompleteTapTree::HiddenParts` error.

I made some changes in branch:
https://github.com/BP-WG/bp-core/pull/25

**Comment by crisdut** [comment]
I made tests, I can transfer and spend UTXO, without "provably unspendable"

**Comment by crisdut** [comment]
@dr-orlovsky,

I found strange behavior in my tests.

I tried to execute `rgb-cli finalize`  with a PSBT file with key-path output (and without taptree defined in the PSBT). The method returns success, but I think is a wrong behavior, because the new output key generated in the `UntweakedPublicKey::convolve_commit` does not use the taptree with the commitment script.

I did try to use **Output::verify** to prevent it but does not work too, I think this scenario causes a non-handle case. 

Could you confirm if tapret need always a taptree?

If always need taptree, I will add the `TaprootBuilder::is_finalized` inside the **XOnlyPublicKey::convolve_commit**.

Thanks

**Comment by dr-orlovsky** [comment]
@crisdut Yes, tapret always need a taptree. If there is no taptree (i.e. no script spending paths) it is created with just a tapret commitment (actually two copies, on the  left and right leaf of the merkle root, since the commitment should always be on the first level below the merkle root).

**Comment by dr-orlovsky** [comment]
Like I did in this early prototype concept: https://github.com/BP-WG/stingerjet-docs
See the end of the README, the tapret final section

**Comment by dr-orlovsky** [comment]
I think I have found a reason of the bug. Please see my two last commits - https://github.com/BP-WG/bp-core/pull/24/commits/559b04b4564559e0be2e85784e74994308388817 and https://github.com/BP-WG/bp-core/pull/24/commits/ee0792f40e8dbd1847dcb6a44751899761409fa3

**Comment by crisdut** [comment]
> I think I have found a reason of the bug. Please see my two last commits - [559b04b](https://github.com/BP-WG/bp-core/commit/559b04b4564559e0be2e85784e74994308388817) and [ee0792f](https://github.com/BP-WG/bp-core/commit/ee0792f40e8dbd1847dcb6a44751899761409fa3)

Good!

I will start some regression tests here.

**Comment by dr-orlovsky** [comment]
@crisdut this is ready for the review. The code needs much more tests, but I think we can start with merging this bugfix, do a release and than add more tests.

**Review by crisdut — APPROVED** [review]

**Pull request merged**
