### PR TITLE
Create Taptree (keypath case)

### PR DESCRIPTION
**Pull request by crisdut**
According to this [comment](https://github.com/BP-WG/bp-core/pull/24#issuecomment-1306904384), I added a change to create a Taptree if does not exist.

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
The code is well-written, but I think I was wrong in my comment there: taptree with a single script puts it into the merkle root. That's why I have an `Option<TapretNodePartner>` and not just `TapretNodePartner`. This also helps to save data on the client-side: proofs will be of zero size for all keypath-only wallets.

So back to the discussion in #24 I think the bug there is caused by a different reason than this one

**Comment by crisdut** [comment]
> The code is well-written, but I think I was wrong in my comment there: taptree with a single script puts it into the merkle root. That's why I have an Option<TapretNodePartner> and not just TapretNodePartner. This also helps to save data on the client-side: proofs will be of zero size for all keypath-only wallets.

Ok, don't worry.

I think the problem is the `convolve_commit` does not working with commitment in merkle root. I will change to handle this case, ok?

**Comment by crisdut** [comment]
I will close to PR, Maxim solved the issue.

**Comment by dr-orlovsky** [comment]
For the record: the solution was in https://github.com/BP-WG/bp-core/pull/24

**Pull request closed without merging**
