### PR TITLE
Make VarInt to be restricted to u32 in length

### PR DESCRIPTION
**Pull request by dr-orlovsky**
This is a quickfix for https://github.com/LNP-BP/client_side_validation/issues/133 to make the things working before we will find a long-term solution at the type level.

For now, the guarantee that the problem doesn't happen elsewhere will be to test all strict types generated lib ids in all consensus repos against predefined constants (they are already in place) in `wasm32`-run tests.

In terms of bitcoin consensus, there are no practical reasons to believe that bitcoin scripts or the number of tx inputs/outputs will ever exceed 4 billions per tx/script; so it Is safe. Anyway, with rust we can't do anything better.

### CODE REVIEW

**Review by cryptoquick — APPROVED** [review]
I think this is the best way.

**Review by crisdut — APPROVED** [review]
Great work!

After merge, we need release a new version to update other stl, like **rgb_contracts** and **rgb_std_stl**.

**Comment by dr-orlovsky** [comment]
Downstreal the stl change without a release since they are generated from the rust types and are not hardcoded. The IDs will change - thus the existing tests will fail, but the crates will still compile and work in a correct way (with the new types).

**Comment by dr-orlovsky** [comment]
So I mean we will need to update them - but just eventually, as a part of the planned release process (maybe alongside adding WASM32 CI running tests).

**Comment by adutravx** [comment]
> So I mean we will need to update them - but just eventually, as a part of the planned release process (maybe alongside adding WASM32 CI running tests).

Sure, I can help you adding wasm32 tests.

**Comment by crisdut** [comment]
> So I mean we will need to update them - but just eventually, as a part of the planned release process (maybe alongside adding WASM32 CI running tests).

Sure, I can help you with this.

**Comment by crisdut** [comment]
> Downstream the stl change without a release since they are generated from the rust types and are not hardcoded. The IDs will change - thus the existing tests will fail, but the crates will still compile and work in the correct way (with the new types).

I'm not sure with I understand.

**Comment by dr-orlovsky** [comment]
Doesn't matter anymore: I already updated & released all crates downstream till RGB Core (which is pending another fix)

**Pull request merged**
